### ISSUE TITLE
`403` Error - Unable to Authenticate

### ISSUE THREAD

**Issue by seanprashad** [JacobLinCool/LeetCode-Query#79]
I'm looking to leverage `LeetCode-Query` for an existing project, however I encounter the following using the minimal example provided:

```js
# example.js

import { LeetCode, Credential } from 'leetcode-query';

const credential = new Credential();
await credential.init('YOUR-LEETCODE-SESSION-COOKIE');

const leetcode = new LeetCode(credential);
console.log(await leetcode.submissions(3, 0));
```

The error is as follows:

```js


$ node example.js

file:///node_modules/leetcode-query/lib/index.js:548
        throw new Error(`HTTP ${res.status} ${res.statusText}: ${await res.text()}`);
              ^

Error: HTTP 403 Forbidden: <!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box;margin:0;padding:0}html{line-height:1.15;-webkit-text-size-adjust:100%;color:#313131}button,html{font-family:system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji}@media (prefers-color-scheme:dark){body{background-color:#222;color:#d9d9d9}body a{color:#fff}body a:hover{color:#ee730a;text-decoration:underline}body .lds-ring div{border-color:#999 transparent transparent}body .font-red{color:#b20f03}body .big-button,body .pow-button{background-color:#4693ff;color:#1d1d1d}body #challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=)}body #challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI0IyMEYwMyIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjQjIwRjAzIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+)}}body{display:flex;flex-direction:column;min-height:100vh}body.no-js .loading-spinner{visibility:hidden}body.no-js .challenge-running{display:none}body.dark{background-color:#222;color:#d9d9d9}body.dark a{color:#fff}body.dark a:hover{color:#ee730a;text-decoration:underline}body.dark .lds-ring div{border-color:#999 transparent transparent}body.dark .font-red{color:#b20f03}body.dark .big-button,body.dark .pow-button{background-color:#4693ff;color:#1d1d1d}body.dark #challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=)}body.dark #challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI0IyMEYwMyIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjQjIwRjAzIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+)}body.light{background-color:transparent;color:#313131}body.light a{color:#0051c3}body.light a:hover{color:#ee730a;text-decoration:underline}body.light .lds-ring div{border-color:#595959 transparent transparent}body.light .font-red{color:#fc574a}body.light .big-button,body.light .pow-button{background-color:#003681;border-color:#003681;color:#fff}body.light #challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=)}body.light #challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI2ZjNTc0YSIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjZmM1NzRhIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+)}a{background-color:transparent;color:#0051c3;text-decoration:none;transition:color .15s ease}a:hover{color:#ee730a;text-decoration:underline}.main-content{margin:8rem auto;max-width:60rem;width:100%}.heading-favicon{height:2rem;margin-right:.5rem;width:2rem}@media (width <= 720px){.main-content{margin-top:4rem}.heading-favicon{height:1.5rem;width:1.5rem}}.footer,.main-content{padding-left:1.5rem;padding-right:1.5rem}.main-wrapper{align-items:center;display:flex;flex:1;flex-direction:column}.font-red{color:#b20f03}.spacer{margin:2rem 0}.h1{font-size:2.5rem;font-weight:500;line-height:3.75rem}.h2{font-weight:500}.core-msg,.h2{font-size:1.5rem;line-height:2.25rem}.body-text,.core-msg{font-weight:400}.body-text{font-size:1rem;line-height:1.25rem}@media (width <= 720px){.h1{font-size:1.5rem;line-height:1.75rem}.h2{font-size:1.25rem}.core-msg,.h2{line-height:1.5rem}.core-msg{font-size:1rem}}#challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI2ZjNTc0YSIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjZmM1NzRhIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+);padding-left:34px}#challenge-error-text,#challenge-success-text{background-repeat:no-repeat;background-size:contain}#challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=);padding-left:42px}.text-center{text-align:center}.big-button{border:.063rem solid #0051c3;border-radius:.313rem;font-size:.875rem;line-height:1.313rem;padding:.375rem 1rem;transition-duration:.2s;transition-property:background-color,border-color,color;transition-timing-function:ease}.big-button:hover{cursor:pointer}.captcha-prompt:not(.hidden){display:flex}@media (width <= 720px){.captcha-prompt:not(.hidden){flex-wrap:wrap;justify-content:center}}.pow-button{background-color:#0051c3;color:#fff;margin:2rem 0}.pow-button:hover{background-color:#003681;border-color:#003681;color:#fff}.footer{font-size:.75rem;line-height:1.125rem;margin:0 auto;max-width:60rem;width:100%}.footer-inner{border-top:1px solid #d9d9d9;padding-bottom:1rem;padding-top:1rem}.clearfix:after{clear:both;content:"";display:table}.clearfix .column{float:left;padding-right:1.5rem;width:50%}.diagnostic-wrapper{margin-bottom:.5rem}.footer .ray-id{text-align:center}.footer .ray-id code{font-family:monaco,courier,monospace}.core-msg,.zone-name-title{overflow-wrap:break-word}@media (width <= 720px){.diagnostic-wrapper{display:flex;flex-wrap:wrap;justify-content:center}.clearfix:after{clear:none;content:none;display:initial;text-align:center}.column{padding-bottom:2rem}.clearfix .column{float:none;padding:0;width:auto;word-break:keep-all}.zone-name-title{margin-bottom:1rem}}.loading-spinner{height:76.391px}.lds-ring{display:inline-block;position:relative}.lds-ring,.lds-ring div{height:1.875rem;width:1.875rem}.lds-ring div{animation:lds-ring 1.2s cubic-bezier(.5,0,.5,1) infinite;border:.3rem solid transparent;border-radius:50%;border-top-color:#313131;box-sizing:border-box;display:block;position:absolute}.lds-ring div:first-child{animation-delay:-.45s}.lds-ring div:nth-child(2){animation-delay:-.3s}.lds-ring div:nth-child(3){animation-delay:-.15s}@keyframes lds-ring{0%{transform:rotate(0)}to{transform:rotate(1turn)}}@media screen and (-ms-high-contrast:active),screen and (-ms-high-contrast:none){.main-wrapper,body{display:block}}</style><meta http-equiv="refresh" content="375"></head><body class="no-js"><div class="main-wrapper" role="main"><div class="main-content"><noscript><div id="challenge-error-title"><div class="h2"><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div></div></noscript></div></div><script>(function(){window._cf_chl_opt={cvId: '3',cZone: "leetcode.com",cType: 'managed',cNounce: '96424',cRay: '862600fa1f1e7114',cHash: '8e35e6f99351f44',cUPMDTk: "\/graphql?__cf_chl_tk=jhhN6l8xNldTjsYRGjsCWpKIfakkhk.XZZ7c.VR.aWA-1710102009-0.0.1.1-1599",cFPWv: 'b',cTTimeMs: '1000',cMTimeMs: '375000',cTplV: 5,cTplB: 'cf',cK: "visitor-time",fa: "\/graphql?__cf_chl_f_tk=jhhN6l8xNldTjsYRGjsCWpKIfakkhk.XZZ7c.VR.aWA-1710102009-0.0.1.1-1599",md: "GvoQVecUsnrqoUnK1R_pKW5ajbUQ8AY1kpPyoUK711w-1710102009-1.1.1.1-QLKECaRLHQNDNRqizKn8plvj8b3.w4lNpZWlb3ebyWN4u05_wsjvhQT76brloXaOtAsHFXSuzQTxd56vdNK34hBSCCoABhoGU.ZM.iAtRC1h9fN5FHYb9Eji1h16bU5F8gMUa_3Fp0ODltQsSkw.rr20W30Eqnb_ruNGgjxRkOtoRl5iW2Wu5AcVddidXH.dXevjYq08l.2bz6jO8e1w0WTQO9nytmQT19Qz7yaxg7hYQsLcvO1rtrwFg1QZ7YPC8wFD8qG4vft6ncNLx2yS57pznEwRtCSPse8XejsZ6MBnaPaUhGRol8Ivb3WulphKFGuSburVrX_9olg8PDxPnKq8KGQAfsWKu7zEZ8pgz48p_fyA7pPIZ87Ci9nlESkBzTf_MMA4VoaTeltkNe5SJGuw7lZAXHrbHO7Mu6icpZUbmo8YMmGOnIqJoF8qIWj5xXylw_gjMkC3IUVGximbe_9yMK09bQ.woYBhkN9_4FpLgJMo_kv9SzP3DJDyffDkTSwp7OuNX62qSKHhIGJqlQaXCNIrdstK9LT9u8S3Tgxf23nbw6HsLXH34Es8_XHuHDv2VxhlEOf9efZAlMWjneIVEmi0h28MjSQsV9YQAS2wmA2vxvXbxWnHn0xlkHIY4E4ZeiAD9yj1R9FXS7N.7S0bQT3GX0Fygw2xs.CuqsyOyVR1ijF3rnB8Lsr__cENWWWBh5DBF9q3svsrpsn6DhVOJMb40JKvmuqgd_nI1FDkf.rm7Hqt.DHaXJCAyJeFxK7W0sK9rDmTyKpb8svJQnfNO_.GlURuIJcDNdbWBZFsmEhcZ4U8OOiq0PGHaqS28e5gXlwpT2mSe0c1oxKr3WGpFk5lclV7TbJNANpSfXNKmHr16vnpEHyY7dVnftNE2feBmMAnCU_38n5EbiJpvphQNTtMUFuQ1ZGnd7QWdN2EX11DDj5UbtzLeLtYEU75hBXiO.7FFkIWOpKCG25GogNKEAmo7fu2xhbuKIoBiSRrHtquZxqUM7Rxh2RABmh4l1Pm3HWdiTK8OUs91ahM2My7faB.IBtdm35HZeluMLxmE77zt75PH7sTWti9mhWo3uCpz_ZAUBjUUGj7bBiDK2H_FYGbe.2v.2_ekQVoqx0HJehmqBMKtAAFw.b_elU9QrBRwzEgmjFCfY5R62z.5Tee3cwGiOHHDctKJitufis_FUYYpw51yfxiMHA5HnkgLraQjEzyCSeY0xCpLiB4iRXSRb5VkgIDO_Wdsap7G.VZLTTlAALkSq4Z.t_pPbCORcw3aOlZVzKTcb5seVXSOWDZXWgKsEUR1pWBPGFaZ8w0nZljRFSmg_dpNII0C1hZ4Qs53wGeZqJ3alSHYdgaCWDNouoGM2TauRcvRDu0vS_CW1SFV7Zq7cayoROkHwv3t9KP7MFwNhbaL24lU.z2qUm5_3wXu8qI9QzuyZFv0rpS.0mfu9wyTmTJgAJdB7SHSqDD.5OrpFYOtr97SsHlFDLfjUFEihu0TMJjB0I0bVd.zwFvvP51tHl0tRLdNdaM",mdrd: "sc_ukARMzT6fRGasPhX8w51EwRFNAgtFGph_MdV2iBI-1710102009-1.1.1.1-ppVPzGPaT31ekcgZA7xyQBjfdyOLUMiAJLg3n4H84vSdbFPv4vsCl2whZaSHurfKnpX0rccqaPEDnVDxJxaw9LdiXKgp1uDDlG.8.rCS0xoybndSE_L59mjAlTofWjy4yvJLUnQkxnfNBNeYa10qPTkg9WKKn9kUznmoQbbvBjrtQ8avf2UTz0k.641lPH.BXYL0UuFH2jzSdpnT.cwrO6pJ7zj.VkZ5xgp0aqT3go39QSbSBfBe8w.ky2IFduJiCPlhjY_tc.xkqCvt_yCFpgQakLgonQsjc5_sor9_7TH24pUsbQXkS22fcZFF4Rqjda22b4a4Z0scDxIc6nupAwDkvvtPpS3kFQB.SVoz8InXLs7C4lEE6DVWCYqv2tK40xnHx4b5sNbtDpW91ok3DfB2qB5z6_7lUx30w0b.twK6OcgLZRolvmzlFYrkN6x38TrYBCA2qNjlb8S7Cr7crdtaLLrP1SfHQ0bRVajyqTmTQ2HnYkuwvDJtXRT1WTf_DMEu8577nIS6fL7C.qcv14ZIgcsowxQIW7OMqfIdnZRpw5dBPcWXfJqVP_W4nA8jX0kEpUqaJW7qI31GmagLj2oKzTU9_RPcwOZqgBz3aagqbgWhU7GmCJvr7UPQlovlhDo8sV0MhbPMa1qE1ZdACRQyityjokUmAzEPQ7Ucb6nJBXC8n3FfvsF2RmwXia9T45KUfr.i5LVUuK5AnMvP_qP18RQsnLeriQhLyQ0flrjcq8hoifmZRWQJRUAoEjeOK86dZVYoUs2cLb9bNFXEwhAbo9R7zWbc6.cePAVYBvoCG60ZAd8O1eyZSf01lZsVvi97yS8jq.9lZoV9n2d4QppTxhCyVr.4TS41JDUxeiysw7DamDzi4ZdqHn9ys2qt35xzrx.vqYjGELBv3TRrOIUtiy1.rog6EtL6wi3cU1LTtbRjNiCvPjCMo.qM6ZJMY0QjsLtBi8QUWdUtcSA8fSUXOfbzneDUMwxE0Mk.rdg7AjxIEqPmIamWqYKSVBEmq0cOFJ1zL1xzt.ix20_03.4FtoYqjCFNYD_PtV35ZkvpQ7lf1A1v.9iLNNLgTYZUuZMPDkyCXtAOgwT83_ctzIpGsPzz4xM_Je1wfIhWGDHSNhDYeVHTgRfp7qguNNrm2lODfoE5RccSnQbsLN.d6lQ1fvQkmI8LiSlDhzldGy79gwOAQsmfIrLVTGDcIkwo_o5LpfXiF7t47ZyprenXLvpikNP0VtnbwieylgwaTt1oWHfqtXVSbiDoApM2QoReshk7sjA5bO1IgOn6__lZ0c4GcXfjkQWf7fZnDO285G74yG7tU_TaV0KXbyZj6S3bH5JdWYuBwTkKWUJIxCngapEtAmrwcLm8tH1unPNcQX3H5EcbaDMmyX_QAsEY3AiBIBU8n3vljaxerVM0HTANyyiF6JnOTHcMwIncU1DvSz3fpOJug4C.cK.MQ9ugg0AxiAwHwIw3ZStVDWPAtANfffo83lEbHIfEnue04VX7wORV8_5k4AOfvluNZo90BRPscYb4RJjGj2dS3eZDhrNt4inIifiCKJrWI9ZzVgqRSX7AsUnFuunuANacfeM2.eC.aWwh3AlX.vaj6SnlpBWt2rkx314Omk6CphFnCY7t3m2vaFetg_3P5IfznFqevbvsW0W7ZclXLfmNO1dz7acLs4O5OiFN.JkOHkpTb.oYo.8t_an9DYFL8sWhfD73CIx1kUfEl5olKTjcg4D41X_.SzeWL7ekVr8DxomxXGQS.1Exijm2Fk7uIaH.B9el648VdKkamU5bA7pB5fqqI3.MKfsCNrJArISlCKmK2oOSKhCBa95wrr8ah3ikmVj.GpN7XfquGz475Rds.JH0hMbuTljl.SOhQp2VU6rgbZW6tL4TKDkS7YpZDnCs2lMfz4GtMrKUrCk49z7xMKWmZUy9XCHS3YDHaxVyMP8yv.eXcBJtyxX3RiAf45uQkB0epsMHaVzH24gezikRyg2ikiOoxHmSojETReUY08yGVA8mbKCM4TDuY_lqeb4CbT_GXCDeASFRRN_84pqqQ6YkPrqq7BCLG97kqkZD7DAnFN22OSf1itF3zSe4elsg.RvVZuCfZrTTgMiNkEoo6Syf1Jq5cTw48UZTlTc9dzLqwviH7JXVkWR7cNBaNVmWms82UFUMSXNfx1UnMKECjPGip1Cy8G7gj8DSh8EqdMjwnsul0_wVKiCPtXfHyoX.LgLUlZu4zhRX4DSGSn3yt8BqYHM9n56kSCs5QL4aUvooUIORk65VTEuywhIBm5wIODzjHQ781jAk_HYRpIvsQiqAjUEUQWQlf7xLlsd_Dm07_m.6nvC7zqmXna4KV88YYMmza4_8WlXHifR2qfigrB8j4s4YoQEq1kW6ZQ3i_va0CJq2Fz.rX0hqHPh8tjty_EdzJaZ6zUIAsIJeTD_OqKiXj4qtZEovvC.DOnKJpnTDwwok5Qp02QK2MFO6v3delocRxTbibIN0h2yIkzRx_Fhhw1Tog2FpQij.s61OtUEyH2KCxkFWDx8D0QHNcd_MtIkDz27jyb.lgUqcPjOZi3jOFhPSpzmR5DqRWjUqKuM24rHET1QaNCCnl09ICWwmgrrxzPswQ44O0SqgVz4CbXHe.a_ha6QIRn8p7bIpZgTaFvcOkjjZx2uwmYaWoWe7lDYoMzsQURcqQKhzA3M801P6bxSeauSGeO8MgQljYnswiMz5DQR8ea.xfy0Zse92FoUwJrctsodCylMO6JT6ng97q4e4sQ",cRq: {ru: 'aHR0cHM6Ly9sZWV0Y29kZS5jb20vZ3JhcGhxbA==',ra: 'TW96aWxsYS81LjAgTGVldENvZGUgQVBJ',rm: 'UE9TVA==',d: 'gbWcbXRm8mAO+ukv4uE9iIYs3fA5+Qx6RuNMAgbTNzEGtoK4bNO0EXxds8pZW+ZDacNcsLS+BdbEll1YnUu8giQVUAtlMjt8pqmJOAFqDUKK+mgFZIuphh5jnYX4CutDxpm+BlWeBeow20U6IsFP9J1Y68rOTNHsCymdGc6wnXE4Z7SLxviIvNxO0lXNH93C3xbcXhFyAcTvFW6PxeQ4zIDTngWP6y8ZGG5Q5y2tYHZksNTfBdkY7HzWPfsPWz8DXS/yj5gDONJ/gWJFvu2CvIEA5yTQUxp+XaqDIUyNklPC0Fg2LWXaiWXYiDSrH6idwj+/OKWcg0JXCp8MNOQKUB05svrIKnU/kyJuq+FYpl1uRU4LYfyR0FMeqvRmoXCYN5eRhuAgDBwZUmTPVjFZMsyWoiJr0LTXMixgMOMQ6pI7mQTHLPDMM/LEmkaQmSReCmoZ3gY/87oLHb9+5rD/A9/7oo7Izuh/2TXrr1bLVGMlZpl7qa6yK6QmKbyUiSfqVNA2vfup7xRDNe0cG4+D+jJPFEPVgaPQrIl4dzVJlfmBKldjsnsQ0pLePso+94taI8PcLJ2OuCDjZIq2L3LGleIYXQeYY4J0JUqPmUvKYS0=',t: 'MTcxMDEwMjAwOS45NjIwMDA=',cT: Math.floor(Date.now() / 1000),m: 'L4rpJpFmBAHECSwc3NfUA8EzHUyLqkC9CzYyLWeNBe8=',i1: 'MV5Ps/8R9ZMUfUZVFJ5Ozw==',i2: 'alZEYzjaXHQAcqN4AQ3VAA==',zh: '6dW5KLsjmoGStZm/w3CUkISq8657AEI6JKhvmam58xM=',uh: 'NtBGM4efBME8d1kUnI82DnS4z1aGeCv1hcc2LqXBS/8=',hh: 'Lb0VxCKQFzTc4iX077lkQv6YXNlmOsxL7hMPdtK/ZKE=',}};var cpo = document.createElement('script');cpo.src = '/cdn-cgi/challenge-platform/h/b/orchestrate/chl_page/v1?ray=862600fa1f1e7114';window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;if (window.history && window.history.replaceState) {var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;history.replaceState(null, null, "\/graphql?__cf_chl_rt_tk=jhhN6l8xNldTjsYRGjsCWpKIfakkhk.XZZ7c.VR.aWA-1710102009-0.0.1.1-1599" + window._cf_chl_opt.cOgUHash);cpo.onload = function() {history.replaceState(null, null, ogU);}}document.getElementsByTagName('head')[0].appendChild(cpo);}());</script></body></html>
    at LeetCode.graphql (file:///node_modules/leetcode-query/lib/index.js:548:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async LeetCode.submissions (file:///node_modules/leetcode-query/lib/index.js:374:24)
    at async file:///example.js:7:13
```

It looks as if CloudFlare is blocking the API from authenticating?

**Comment by JacobLinCool** [comment]
LeetCode started to block some IPs a few days ago. You might want to try to use custom fetcher for making requests: https://github.com/JacobLinCool/LeetCode-Query?tab=readme-ov-file#use-custom-fetcher

**Comment by JacobLinCool** [comment]
I was facing the same problem and fixed it by moving the service to a different cloud.
See https://github.com/JacobLinCool/LeetCode-Stats-Card/issues/115#issuecomment-1984064385

**Comment by seanprashad** [comment]
Thanks for these links @JacobLinCool!

I encountered this error both for your repo, as well as a [script I own](https://github.com/seanprashad/leetcode-patterns/blob/main/cron/update_questions.py) which runs via GitHub Actions. Weirdly enough, this Python script worked locally for a short period of time before the Captcha from CloudFlare workers appeared, which made me check out how other libraries are handling this.
