### ISSUE TITLE
leetcode.whoami() is not working.

### ISSUE THREAD

**Issue by JaySabva** [JacobLinCool/LeetCode-Query#91]
```js
const { LeetCode, Credential } = require("leetcode-query");

async function fetchWhoAmI(cookie) {
    const credential = new Credential();
    await credential.init(cookie);
    
    const leetcode = new LeetCode(credential);

    try {
        let response = await leetcode.whoami();
        console.log(response);
    } catch (error) {
        console.error("Error fetching user info:", error);
    }
}

fetchWhoAmI(cookie);
```

Error Log
```js
Error fetching user info: Error: HTTP 400 Bad Request: {"errors":[{"message":"Unknown operation named \"globalData\"."}]}
    at LeetCode.graphql (c:\Users\node_modules\leetcode-query\lib\index.cjs:589:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async LeetCode.whoami (c:\Users\node_modules\leetcode-query\lib\index.cjs:558:22)
    at async fetchWhoAmI (c:\Users\lcext.js:10:24)
```

**Comment by JaySabva** [comment]
@JacobLinCool any update?
