### ISSUE TITLE
Unable to get User Information

### ISSUE THREAD

**Issue by AnuragAnalog** [JacobLinCool/LeetCode-Query#93]
# Unable to get user information

## Code used to reproduce
```js
import { LeetCode } from "leetcode-query";

const leetcode = new LeetCode();
const user = await leetcode.user("username");
```

## Error

```bash
Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'Window': Illegal invocation
    at _fetch (index.js:71:1)
    at get_csrf (index.js:87:1)
    at Credential.init (index.js:111:1)
    at getUser (Card.js:10:1)
    at Card (Card.js:15:1)
    at renderWithHooks (react-dom.development.js:15486:1)
    at mountIndeterminateComponent (react-dom.development.js:20103:1)
    at beginWork (react-dom.development.js:21626:1)
    at beginWork$1 (react-dom.development.js:27465:1)
    at performUnitOfWork (react-dom.development.js:26596:1)
```

Help me with this. @JacobLinCool

**Comment by JacobLinCool** [comment]
Hello. Which environment did you run it on? I tested it, and the code works on Node, Deno, and Bun without any problems.

**Comment by diragb** [comment]
facing a similar issue, this is on nextjs

**Comment by AnuragAnalog** [comment]
> Hello. Which environment did you run it on? I tested it, and the code works on Node, Deno, and Bun without any problems.

I tried to run the code in React, and I was facing error, the react boilerplate code was created using create-react-app.

**Comment by JacobLinCool** [comment]
Ok, please check the following:

1. It may not be possible to use it in the browser due to the CORS problem; please run it in the server environment instead.
2. If you still encounter this issue on the server side, please try using a custom fetcher:

```ts
import { LeetCode, fetcher } from "leetcode-query";

// use a custom fetcher
fetcher.set(fetch);

// use as normal
const lc = new LeetCode();
const daily = await lc.daily();
console.log(daily);
```
